repositories:
  - name: tacokumo
    url: https://tacokumo.github.io/helm-charts

releases:
  - name: portal
    namespace: sample-project
    chart: tacokumo/tacokumo-portal
    version: 0.3.0
    values:
    - ./values/tacokumo-portal.yaml
  - name: portal-controller-kubernetes
    namespace: portal-controller-system
    chart: tacokumo/portal-controller-kubernetes
    version: 0.8.0
    values:
    - ./values/portal-controller-kubernetes.yaml
  - name: eg
    namespace: envoy-gateway-system
    chart: oci://docker.io/envoyproxy/gateway-helm
    version: v1.7.0
    values:
    - ./values/envoy-gateway.yaml
  - name: portal-proxy
    namespace: portal-proxy
    chart: tacokumo/tacokumo-portal-proxy
    version: 0.2.0
    values:
    - ./values/tacokumo-portal-proxy.yaml
